#!/usr/bin/env bash
set -e

if [ "$LOGNAME" != "root" ]; then
    echo "Error: MUST run as root user."
    exit 1
fi

_OUTPUT_NAME="ndi_receiver_v4"
_SOURCE_CODE="ndi_receiver_v4.cpp"
_HOME="/home/ndpi-client"

cd $_HOME/ndpi/ndi_receiver_v3__NDI6

rm -f $_OUTPUT_NAME

if ! g++ \
    -o $_OUTPUT_NAME $_SOURCE_CODE \
    $(pkg-config --cflags --libs gstreamer-1.0 gstreamer-app-1.0) \
    -I"include" \
    -ldl \
    -std=c++11 \
; then
    cd $_HOME
    exit 1
else
    echo ""
    echo "-- Successful Compilation"
    echo "Use the following line to execute."
    echo "cd $(pwd) && ./${_OUTPUT_NAME}"
    cd $_HOME
    exit 0
fi