#!/usr/bin/env bash

export DISPLAY=:0

# List Connected Display
#   -F (Fixed Strings): Searches for 'connected' as a single string
#   -w (Whole Word): Searches for 'connected' as a complete word (disregarding 'disconnected')
echo "$(xrandr | grep -Fw 'connected' | awk '{print "current_output :", $1}')"
#

# Current Resolution
echo "$(xrandr | grep '*' | awk '{print "current_resolution :", $1}')"
echo "$(xrandr | grep -oP '[0-9.]+(?=\*)' | awk '{print "current_framerate :", $1}')"
#
# Preferred Resolution
echo "$(xrandr | grep '+ ' | awk '{print "preferred_resolution :", $1}')"
echo "$(xrandr | grep '+ ' | awk '{print "preferred_framerate :", $2}')"
#

cd /sys/class/hwmon && cat hwmon0/temp1_input

# List Resolutions
#   -v (Invert Match): Removes lines containg the letter 'm'
echo "$(xrandr | grep -v 'm' | awk '{print "list_resolutions :", $1, "::", "--mode", $1, "--rate", $2}')"
  # Example Return:
    # list_resolutions : 1920x1080 :: --mode 1920x1080 --rate 60.00*+
    # list_resolutions : 1680x1050 :: --mode 1680x1050 --rate 59.88
    # list_resolutions : 1600x900  :: --mode 1600x900  --rate 60.00
    # list_resolutions : 1280x1024 :: --mode 1280x1024 --rate 60.02
    # list_resolutions : 1440x900  :: --mode 1440x900  --rate 59.90
    # list_resolutions : 1366x768  :: --mode 1366x768  --rate 59.96
    # list_resolutions : 1280x800  :: --mode 1280x800  --rate 59.91
    # list_resolutions : 1152x864  :: --mode 1152x864  --rate 59.97
    # list_resolutions : 1280x720  :: --mode 1280x720  --rate 60.00
    # list_resolutions : 1024x768  :: --mode 1024x768  --rate 60.00
    # list_resolutions : 800x600   :: --mode 800x600   --rate 60.32
    # list_resolutions : 720x576   :: --mode 720x576   --rate 50.00
    # list_resolutions : 720x480   :: --mode 720x480   --rate 60.00
    # list_resolutions : 640x480   :: --mode 640x480   --rate 60.00
#

#  cec-client
#
#   Example Command: 
#       echo "on 0" | cec-client -s -d 1
#       echo "as" | cec-client -s -d 1
#
#   Minimal Console Output Interactive Shell:
#       cec-client | grep -vE 'DEBUG:|TRAFFIC:'
#
#  ================================================================================
#  Available commands:
#  
#  [tx] {bytes}             transfer bytes over the CEC line.
#  [txn] {bytes}            transfer bytes but don't wait for transmission ACK.
#  [on] {address}           power on the device with the given logical address.
#  [standby] {address}      put the device with the given address in standby mode.
#  [la] {logical address}   change the logical address of the CEC adapter.
#  [p] {device} {port}      change the HDMI port number of the CEC adapter.
#  [pa] {physical address}  change the physical address of the CEC adapter.
#  [as]                     make the CEC adapter the active source.
#  [is]                     mark the CEC adapter as inactive source.
#  [osd] {addr} {string}    set OSD message on the specified device.
#  [ver] {addr}             get the CEC version of the specified device.
#  [ven] {addr}             get the vendor ID of the specified device.
#  [lang] {addr}            get the menu language of the specified device.
#  [pow] {addr}             get the power status of the specified device.
#  [name] {addr}            get the OSD name of the specified device.
#  [poll] {addr}            poll the specified device.
#  [lad]                    lists active devices on the bus
#  [ad] {addr}              checks whether the specified device is active.
#  [at] {type}              checks whether the specified device type is active.
#  [sp] {addr}              makes the specified physical address active.
#  [spl] {addr}             makes the specified logical address active.
#  [volup]                  send a volume up command to the amp if present
#  [voldown]                send a volume down command to the amp if present
#  [mute]                   send a mute/unmute command to the amp if present
#  [self]                   show the list of addresses controlled by libCEC
#  [scan]                   scan the CEC bus and display device info
#  [mon] {1|0}              enable or disable CEC bus monitoring.
#  [log] {1 - 31}           change the log level. see cectypes.h for values.
#  [ping]                   send a ping command to the CEC adapter.
#  [bl]                     to let the adapter enter the bootloader, to upgrade the flash rom.
#  [r]                      reconnect to the CEC adapter.
#  [h] or [help]            show this help.
#  [q] or [quit]            to quit the CEC test client and switch off all connected CEC devices.
#  ================================================================================


# hostnamectl
#  Static hostname: NDPi-Server
#        Icon name: computer
#       Machine ID: 5c2c9c075d03474396188cda33e732be
#          Boot ID: af61e2c3a2cc4212bb47c3549f9f9e3c
# Operating System: Debian GNU/Linux 13 (trixie)    
#           Kernel: Linux 6.12.75+rpt-rpi-2712
#     Architecture: arm64

# uptime -p
# up 49 minutes
